version: "3.7"
services:

  rathena-server:
    image: cbrgm/rathena-server:latest
    restart: unless-stopped
    depends_on:
      - rathena-mysql
    ports:
      - 6900:6900
      - 6121:6121
      - 5121:5121
    environment:
      - MYSQL_HOST=172.20.0.10
      - MYSQL_USER=root
      - MYSQL_PWD=secret
      - MYSQL_DB=rAthena
      - MYSQL_DROP_DB=0
      - NETWORK_CHAR_TO_LOGIN_IP=127.0.0.1
      - NETWORK_MAP_TO_CHAR_IP=127.0.0.1
      - NETWORK_CHAR_PUBLIC_IP=192.168.188.62
      - NETWORK_MAP_PUBLIC_IP=192.168.188.62
      - NETWORK_ADD_SUBNET_MAP1=
      - SERVER_NAME=NorthRO
      - SERVER_MOTD=Welcome to NorthRO Ragnarok Online!
      - SERVER_INTERSRV_USERID=intersrv
      - SERVER_INTERSRV_PASSWD=intersrv
      - SERVER_MAX_CONNECT_USER=1024
      - SERVER_GM_USER=Godfather
      - SERVER_GM_PASSWD=secret
      - SERVER_CHAR_NEW=yes
      - SERVER_START_ZENY=5000
      - SERVER_START_POINT=prontera,155,182
      - SERVER_START_POINT_PRE=prontera,155,182
      - SERVER_START_POINT_DORAM=
      - SERVER_START_ITEMS=
      - SERVER_START_ITEMS_DORAM=
      - SERVER_PINCODE_ENABLED=no
      - SERVER_LOGIN_ALLOWED_REGS=1
      - SERVER_LOGIN_TIME_ALLOWED=10
      - SERVER_LOGIN_MD5_PASSWD=no
      - CONFIG_DROPS_ITEM_RATE_COMMON=1000
      - CONFIG_DROPS_ITEM_RATE_COMMON_BOSS=1000
      - CONFIG_DROPS_ITEM_RATE_COMMON_MVP=1000
      - CONFIG_DROPS_ITEM_RATE_HEAL=1000
      - CONFIG_DROPS_ITEM_RATE_HEAL_BOSS=1000
      - CONFIG_DROPS_ITEM_RATE_HEAL_MVP=1000
      - CONFIG_DROPS_ITEM_RATE_USE=1000
      - CONFIG_DROPS_ITEM_RATE_USE_BOSS=1000
      - CONFIG_DROPS_ITEM_RATE_USE_MVP=1000
      - CONFIG_DROPS_ITEM_RATE_EQUIP=3000
      - CONFIG_DROPS_ITEM_RATE_EQUIP_BOSS=5000
      - CONFIG_DROPS_ITEM_RATE_EQUIP_MVP=15000
      - CONFIG_DROPS_ITEM_RATE_CARD=20000
      - CONFIG_DROPS_ITEM_RATE_CARD_BOSS=100000
      - CONFIG_DROPS_ITEM_RATE_CARD_MVP=250000
      - CONFIG_DROPS_ITEM_RATE_MVP=100000
      - CONFIG_DROPS_ITEM_RATE_ADDDROP=100000
      - CONFIG_DROPS_ITEM_RATE_TREASURE=100000
      - CONFIG_EXP_BASE_EXP_RATE=2000
      - CONFIG_EXP_JOB_EXP_RATE=2000
      - CONFIG_EXP_MVP_EXP_RATE=2000
      - CONFIG_EXP_QUEST_EXP_RATE=5000
      - CONFIG_EXP_MULTI_LEVEL_UP=no
      - CONFIG_EXP_HEAL_EXP=0
      - CONFIG_EXP_RESURRECTION_EXP=0
      - CONFIG_EXP_SHOP_EXP=0
      - CONFIG_EXP_PVP_EXP=yes
      - CONFIG_EXP_DEATH_PENALTY_TYPE=1
      - CONFIG_EXP_DEATH_PENALTY_BASE=100
      - CONFIG_EXP_DEATH_PENALTY_JOB=100
      - CONFIG_EXP_ZENY_PENALTY=0
      - CONFIG_EXP_DISP_EXPERIENCE=yes
    networks:
      rathena-network:
        ipv4_address: 172.20.0.20

#  rathena-fluxcp:
#    image: cbrgm/rathena-fluxcp
#    restart: unless-stopped
#    depends_on:
#      - rathena-mysql
#    ports:
#      - 8080:80
#    environment:
#      - SERVER_NAME=NorthRO
#      - SERVER_BASE_DIR=fluxcp
#      - SERVER_ADDRESS=localhost:80
#      - MYSQL_HOST=172.20.0.10
#      - MYSQL_DB=rAthena
#      - MYSQL_USER=root
#      - MYSQL_PWD=secret
#      - SVR_LOGIN_ADDR=172.20.0.20
#      - SVR_CHAR_ADDR=172.20.0.20
#      - SVR_MAP_ADDR=172.20.0.20
#      - INSTALLER_PWD=secret
#    networks:
#      - rathena-network

  rathena-mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      rathena-network:
        ipv4_address: 172.20.0.10

  rathena-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - rathena-mysql
    ports:
      - 15000:80
    environment:
      - PMA_HOST=172.20.0.10
    networks:
      - rathena-network

networks:
  rathena-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
