targets = server config mysql

all : server

build:
	docker build -t "cbrgm/rathena-server:latest" .

mysql:
	docker run -p 3306 --name "mysql" -e MYSQL_ROOT_PASSWORD="secret" -v "${pwd}/data:/var/lib/mysql" -d mysql:5.7

mysql-stop:
	docker stop mysql; docker rm mysql

rathena:
	docker run -d -p 6900:6900 -p 6121:6121 -p 5121:5121 --restart=unless-stopped --name rathena \
	-e MYSQL_HOST="172.17.0.2" \
	-e MYSQL_USER="root" \
	-e MYSQL_PWD="secret" \
	-e MYSQL_DB="rAthena" \
	-e MYSQL_DROP_DB=0 \
	-e NETWORK_CHAR_TO_LOGIN_IP="127.0.0.1" \
	-e NETWORK_MAP_TO_CHAR_IP="127.0.0.1" \
	-e NETWORK_CHAR_PUBLIC_IP="192.168.188.62" \
	-e NETWORK_MAP_PUBLIC_IP="192.168.188.62" \
	-e NETWORK_ADD_SUBNET_MAP1="" \
	-e SERVER_NAME="NorthRO" \
	-e SERVER_MOTD="Welcome to NorthRO Ragnarok Online!" \
	-e SERVER_INTERSRV_USERID="intersrv" \
	-e SERVER_INTERSRV_PASSWD="intersrv" \
	-e SERVER_MAX_CONNECT_USER=1024 \
	-e SERVER_GM_USER="Godfather" \
	-e SERVER_GM_PASSWD="secret" \
	-e SERVER_CHAR_NEW="yes" \
	-e SERVER_START_ZENY=5000 \
	-e SERVER_START_POINT="prontera,155,182" \
	-e SERVER_START_POINT_PRE="prontera,155,182" \
	-e SERVER_START_POINT_DORAM="" \
	-e SERVER_START_ITEMS="" \
	-e SERVER_START_ITEMS_DORAM="" \
	-e SERVER_PINCODE_ENABLED="no" \
	-e SERVER_LOGIN_ALLOWED_REGS="1" \
	-e SERVER_LOGIN_TIME_ALLOWED="10" \
	-e SERVER_LOGIN_MD5_PASSWD="no" \
	-e CONFIG_DROPS_ITEM_RATE_COMMON="1000" \
	-e CONFIG_DROPS_ITEM_RATE_COMMON_BOSS="1000" \
	-e CONFIG_DROPS_ITEM_RATE_COMMON_MVP="1000" \
	-e CONFIG_DROPS_ITEM_RATE_HEAL="1000" \
	-e CONFIG_DROPS_ITEM_RATE_HEAL_BOSS="1000" \
	-e CONFIG_DROPS_ITEM_RATE_HEAL_MVP="1000" \
	-e CONFIG_DROPS_ITEM_RATE_USE="1000" \
	-e CONFIG_DROPS_ITEM_RATE_USE_BOSS="1000" \
	-e CONFIG_DROPS_ITEM_RATE_USE_MVP="1000" \
	-e CONFIG_DROPS_ITEM_RATE_EQUIP="3000" \
	-e CONFIG_DROPS_ITEM_RATE_EQUIP_BOSS="5000" \
	-e CONFIG_DROPS_ITEM_RATE_EQUIP_MVP="15000" \
	-e CONFIG_DROPS_ITEM_RATE_CARD="20000" \
	-e CONFIG_DROPS_ITEM_RATE_CARD_BOSS="100000" \
	-e CONFIG_DROPS_ITEM_RATE_CARD_MVP="250000" \
	-e CONFIG_DROPS_ITEM_RATE_MVP="100000" \
	-e CONFIG_DROPS_ITEM_RATE_ADDDROP="100000" \
	-e CONFIG_DROPS_ITEM_RATE_TREASURE="100000" \
	-e CONFIG_EXP_BASE_EXP_RATE="2000" \
	-e CONFIG_EXP_JOB_EXP_RATE="2000" \
	-e CONFIG_EXP_MVP_EXP_RATE="2000" \
	-e CONFIG_EXP_QUEST_EXP_RATE="5000" \
	-e CONFIG_EXP_MULTI_LEVEL_UP="no" \
	-e CONFIG_EXP_HEAL_EXP="0" \
	-e CONFIG_EXP_RESURRECTION_EXP="0" \
	-e CONFIG_EXP_SHOP_EXP="0" \
	-e CONFIG_EXP_PVP_EXP="yes" \
	-e CONFIG_EXP_DEATH_PENALTY_TYPE="1" \
	-e CONFIG_EXP_DEATH_PENALTY_BASE="100" \
	-e CONFIG_EXP_DEATH_PENALTY_JOB="100" \
	-e CONFIG_EXP_ZENY_PENALTY="0" \
	-e CONFIG_EXP_DISP_EXPERIENCE="yes" \
	cbrgm/rathena:latest

rathena-stop:
	docker stop rathena; docker rm rathena
